### ISSUE TITLE
203 Connecting your VPC to the Internet using an Internet Gateway

### ISSUE THREAD

**Issue by KenTsuRinn** [AWSCookbook/Networking#1]
**Describe the bug**
In the Section, Connecting your VPC to the Internet using an Internet Gateway, we need pip install -r requirements.txt --no-dependencies. But in my personal PC, it will throw error "AttributeError: module 'constructs' has no attribute 'ISynthesisSession'
". 
 
**How to Fix it**
In personal environment, there would like to lost dependencies with cdk. So when we  should better to execute "pip install -r requirements.txt".

**Comment by johnculkin** [comment]
Thanks Ken! 

We have improved things by upgrading to the CDK 2.0 which makes dealing with dependencies much easier 
https://github.com/aws/aws-cdk/projects/10
